### ISSUE TITLE
Linux NativeAuthorization 

### ISSUE THREAD

**Issue by bmbowdish** [Simont3/hcpsdk#2]
[bbowdish@devpulp01 ~]$ python3.6 hcpxfer.py download hcpxfer.exe hcpxfer.exe
Traceback (most recent call last):
  File "hcpxfer.py", line 109, in <module>
    main()
  File "hcpxfer.py", line 36, in main
    auth = hcpsdk.NativeAuthorization(config['hcp_user'], config['hcp_password'])
AttributeError: module 'hcpsdk' has no attribute 'NativeAuthorization'

I am not having this issue on Windows or MacOS

**Comment by bmbowdish** [comment]
Its almost like it doesn't think the function is there at all on Linux.

**Comment by bmbowdish** [comment]
[bbowdish@devpulp01 ~]$ python3.6
Python 3.6.5 (default, Apr 10 2018, 17:08:37)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-16)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import hcpsdk
>>> hcpsdk.version()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'hcpsdk' has no attribute 'version'
>>> hcpsdk
<module 'hcpsdk' (namespace)>
>>>
